[build-system]
requires = ["hatchling", "hatch-polylith-bricks"]
build-backend = "hatchling.build"

[project]
name = "api_public"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
    "aiokafka==0.12.0",
    "aiokafkaengine==0.0.4",
    "fastapi==0.115.12",
    "pydantic-settings==2.9.1",
    "sqlalchemy==2.0.44",
    "uvicorn==0.34.2",
    "asyncmy==0.2.11",
    "orjson==3.10.16",
    "prometheus-client==0.22.0",
]

[project.scripts]
scrape_task_producer = "bot_detector.api_public.core.server:run"

[tool.hatch.build.hooks.polylith-bricks]
packages = ["bot_detector"]

[tool.polylith.bricks]
"../../bases/bot_detector/api_public" = "bot_detector/api_public"
"../../components/bot_detector/database" = "bot_detector/database"
"../../components/bot_detector/kafka" = "bot_detector/kafka"
"../../components/bot_detector/structs" = "bot_detector/structs"
"../../components/bot_detector/logfmt" = "bot_detector/logfmt"
