[build-system]
requires = ["hatchling", "hatch-polylith-bricks"]
build-backend = "hatchling.build"

[project]
name = "job_hs_migration_v3"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
    "aiokafkaengine==0.1.0",
    "asyncmy==0.2.10",
    "cryptography==44.0.1",
    "pydantic-settings==2.7.0",
    "pydantic==2.10.4",
    "sqlalchemy==2.0.44",
    "orjson==3.10.16",
]

[project.scripts]
job_hs_migration_v3 = "bot_detector.job_hs_migration_v3.core:run"

# This section is needed for building
[tool.hatch.build.targets.wheel]
packages = ["bot_detector"]

[tool.hatch.build.hooks.polylith-bricks]

[tool.polylith.bricks]
"../../bases/bot_detector/job_hs_migration_v3" = "bot_detector/job_hs_migration_v3"
"../../components/bot_detector/core" = "bot_detector/core"
"../../components/bot_detector/kafka" = "bot_detector/kafka"
"../../components/bot_detector/player" = "bot_detector/player"
"../../components/bot_detector/highscore_worker" = "bot_detector/highscore_worker"
