services:
  kafka:
    container_name: kafka
    image: bitnami/kafka:3.5.1-debian-11-r3
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      # volumes:
      #   - ./kafka:/bitnami/kafka:rw
    ports:
      - 9094:9094
      - 9092:9092
    healthcheck:
      test:
        [
          "CMD",
          "kafka-topics.sh",
          "--list",
          "--bootstrap-server",
          "localhost:9092"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - botdetector-network

  kafka_setup:
    container_name: kafka_setup
    image: bd/kafka_setup # tags the image if build
    build:
      context: ./_kafka
    # command: ["sleep", "infinity"]
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - botdetector-network
    depends_on:
      kafka:
        condition: service_healthy

  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop:latest
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
    ports:
      - 9000:9000
    restart: on-failure
    networks:
      - botdetector-network
    depends_on:
      kafka:
        condition: service_healthy

  hiscore_scraper:
    container_name: hiscore_scraper
    image: bd/hiscore_scraper # tags the image if build
    build:
      context: ./
      dockerfile: ./projects/hiscore_scraper/Dockerfile
    # command: ["sleep", "infinity"]
    networks:
      - botdetector-network
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
  
  project_debugger:
    container_name: anything_debug
    image: bd/anything_debug # tags the image if build
    build:
      context: ./
      dockerfile: Dockerfile
    # command: ["uv", "run", "bases/bot_detector/hiscore_scraper/core.py"]
    command: ["sleep", "infinity"]
    networks:
      - botdetector-network
    env_file:
      - .env
    # depends_on:
    #   kafka:
    #     condition: service_healthy
networks:
  botdetector-network:
    name: bd-network