services:
  opencode:
    network_mode: host
    build:
      context: .
      dockerfile: _opencode/Dockerfile
      target: final
    image: my_opencode
    volumes:
      # opencode source code
      - ./_opencode/.opencode:/home/opencode/project/.opencode
      - ./_opencode/Dockerfile:/home/opencode/project/_opencode/Dockerfile
      - ./_opencode/src:/home/opencode/project/_opencode/src
      - ./_opencode/opencode.jsonc:/home/opencode/project/opencode.jsonc
      - ./_opencode/specs:/home/opencode/project/specs
      - ./_opencode/memory:/home/opencode/project/memory
      - opencode_auth:/home/opencode/.local/share/opencode
      - ./AGENTS.md:/home/opencode/project/AGENTS.md
      # project source code
      - ./bases:/home/opencode/project/bases
      - ./components:/home/opencode/project/components
      - ./projects:/home/opencode/project/projects
      - ./test:/home/opencode/project/test
      - ./uv.lock:/home/opencode/project/uv.lock
      - ./pyproject.toml:/home/opencode/project/pyproject.toml
      - ./workspace.toml:/home/opencode/project/workspace.toml:ro
      # infrastructure
      - ./_kafka:/home/opencode/project/_kafka
      - ./_mysql:/home/opencode/project/_mysql
      # configs and docs
      - ./docker-compose.yml:/home/opencode/project/docker-compose.yml
      - ./docker-compose-oc.yml:/home/opencode/project/docker-compose-oc.yml
      - ./docker-compose-dev.yml:/home/opencode/project/docker-compose-dev.yml
      - ./docker-compose-debug.yml:/home/opencode/project/docker-compose-debug.yml
      - ./README.md:/home/opencode/project/README.md
    env_file:
      - ./_opencode/.env
    # Equivalent to -it
    stdin_open: true
    tty: true

volumes:
  # volume to persist opencode auth data
  opencode_auth: