services:
  kafka:
    image: apache/kafka:3.7.2
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - 9092:9092
    healthcheck:
      test:
        [
          "CMD",
          "./opt/kafka/bin/kafka-topics.sh",
          "--list",
          "--bootstrap-server",
          "localhost:9092"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - botdetector-network

  kafka_setup:
    container_name: kafka_setup
    image: bd/kafka_setup # tags the image if build
    build:
      context: ./_kafka
    # command: ["sleep", "infinity"]
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - botdetector-network
    depends_on:
      kafka:
        condition: service_healthy

  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop:latest
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
    ports:
      - 9000:9000
    restart: on-failure
    networks:
      - botdetector-network
    depends_on:
      kafka:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: bd/mysql # tags the image if build
    build:
      context: ./_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_bot_buster
      # - MYSQL_DATABASE=playerdata
    volumes:
      - ./_mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    networks:
      - botdetector-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot_bot_buster"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s
  mysql_setup:
    container_name: mysql_setup
    image: bd/mysql_setup # tags the image if build
    build:
      context: ./_mysql_data
    # command: ["sleep", "infinity"]
    environment:
      - DATABASE_URL=mysql+asyncmy://root:root_bot_buster@mysql:3306/playerdata
      - DEBUG=False
    networks:
      - botdetector-network
    depends_on:
      mysql:
        condition: service_healthy

  hiscore_scraper:
    container_name: hiscore_scraper
    image: bd/hiscore_scraper # tags the image if build
    build:
      context: ./
      dockerfile: ./projects/hiscore_scraper/Dockerfile
      target: production
    # command: ["sleep", "infinity"]
    networks:
      - botdetector-network
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
  runemetrics_scraper:
    container_name: runemetrics_scraper
    image: bd/runemetrics_scraper # tags the image if build
    build:
      context: ./
      dockerfile: ./projects/runemetrics_scraper/Dockerfile
      target: production
    # command: ["sleep", "infinity"]
    networks:
      - botdetector-network
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
  hiscore_worker:
    container_name: hiscore_worker
    image: bd/hiscore_worker # tags the image if build
    build:
      context: ./
      dockerfile: ./projects/hiscore_worker/Dockerfile
      target: production
    # command: ["sleep", "infinity"]
    networks:
      - botdetector-network
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_healthy
  scrape_task_producer:
    container_name: scrape_task_producer
    image: bd/scrape_task_producer # tags the image if build
    build:
      context: ./
      dockerfile: ./projects/scrape_task_producer/Dockerfile
      target: production
    # command: ["sleep", "infinity"]
    networks:
      - botdetector-network
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_healthy 
      mysql_setup:
        condition: service_completed_successfully
networks:
  botdetector-network:
    name: bd-network