services:
  opencode:
    build:
      context: .
      dockerfile: _opencode/Dockerfile
    image: my_opencode
    volumes:
      # Use ./ to indicate local relative paths
      - ./_opencode/.opencode:/opencode/.opencode
      - ./bases:/opencode/bases
      - ./components:/opencode/components
      - ./projects:/opencode/projects
      - ./test:/opencode/test
      - ./_kafka:/opencode/_kafka
      - ./_minio_data:/opencode/_minio_data
      - ./_mysql:/opencode/_mysql
      - ./uv.lock:/opencode/uv.lock
      - ./pyproject.toml:/opencode/pyproject.toml
      - ./workspace.toml:/opencode/workspace.toml
      - ./docker-compose.yml:/opencode/docker-compose.yml
      - ./README.md:/opencode/README.md
    env_file:
      - ./_opencode/.env
    # Equivalent to -it
    stdin_open: true
    tty: true
    working_dir: /opencode