[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bot-detector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.11.11",
    "aiokafkaengine>=0.1.0",
    "asyncmy>=0.2.10",
    "cryptography>=44.0.0",
    "osrs>=0.0.15",
    "pydantic-settings>=2.7.0",
    "pydantic>=2.10.4",
    "sqlalchemy>=2.0.37",
    "orjson>=3.10.15",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
    "prometheus-client>=0.21.1",
]

[dependency-groups]
dev = [
    "kafka-python>=2.0.2",
    "polylith-cli>=1.30.1",
    "pytest>=8.3.4",
    "ruff>=0.8.4",
    "pytest-asyncio>=0.25.0",
    "pytest-cov>=6.1.1",
    "httpx>=0.27.0",
]



[tool.hatch.build]
dev-mode-dirs = ["components", "bases", "development", "."]


[tool.hatch.metadata]
allow-direct-references = true

[tool.polylith.bricks]
"bases/bot_detector/api_public" = "bot_detector/api_public"
"bases/bot_detector/runemetrics_scraper" = "bot_detector/runemetrics_scraper"
"bases/bot_detector/hiscore_worker" = "bot_detector/hiscore_worker"
"bases/bot_detector/api_private" = "bot_detector/api_private"
"bases/bot_detector/scrape_task_producer" = "bot_detector/scrape_task_producer"
"bases/bot_detector/hiscore_scraper" = "bot_detector/hiscore_scraper"
"components/bot_detector/feedback" = "bot_detector/feedback"
"components/bot_detector/proxy_manager" = "bot_detector/proxy_manager"
"components/bot_detector/structs" = "bot_detector/structs"
"components/bot_detector/kafka" = "bot_detector/kafka"
"components/bot_detector/kafka_client" = "bot_detector/kafka_client"
"components/bot_detector/runemetrics_api" = "bot_detector/runemetrics_api"
"components/bot_detector/logfmt" = "bot_detector/logfmt"
"components/bot_detector/database" = "bot_detector/database"
