[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bot-detector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "api_public",
    "api_ml",
    "worker_hiscore",
    "worker_ml",
    "worker_report",
    "hiscore_scraper",
    "runemetrics_scraper",
    "scrape_task_producer",
    "website",
    "job_hs_migration_v3",
    "job_prune_hs_data",
]

[dependency-groups]
dev = [
    "kafka-python>=2.0.2",
    "polylith-cli>=1.24.0",
    "pytest>=8.3.4",
    "ruff>=0.8.4",
    "pytest-asyncio>=0.25.0",
    "pytest-cov>=6.1.1",
    "mypy>=1.19.1",
    "pyright>=1.1.408",
]

[tool.uv.sources]
api_public = { path = "./projects/api_public" }
api_ml = { path = "./projects/api_ml" }
worker_hiscore = { path = "./projects/worker_hiscore" }
worker_ml = { path = "./projects/worker_ml" }
worker_report = { path = "./projects/worker_report" }
hiscore_scraper = { path = "./projects/hiscore_scraper" }
runemetrics_scraper = { path = "./projects/runemetrics_scraper" }
scrape_task_producer = { path = "./projects/scrape_task_producer" }
website = { path = "./projects/website" }
job_hs_migration_v3 = { path = "./projects/job_hs_migration_v3" }
job_prune_hs_data = { path = "./projects/job_prune_hs_data" }


[tool.hatch.build]
dev-mode-dirs = ["components", "bases", "development", "."]


[tool.hatch.metadata]
allow-direct-references = true
