{
 "title": "app-metrics-api",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "public api requests per second [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(request_count_total{container=\"public-api\"}[5m]))",
     "legendFormat": "requests/second"
    }
   ]
  },
  {
   "title": "requests per second by endpoint and status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (exported_endpoint, http_status) (rate(request_count_total{container=\"public-api\", http_status!=\"404\"}[5m]))",
     "legendFormat": "[{{http_status}}] {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "api latency quantiles [15m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(request_latency_seconds_bucket{container=\"public-api\", http_status!=\"404\"}[15m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(request_latency_seconds_bucket{container=\"public-api\", http_status!=\"404\"}[15m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(request_latency_seconds_bucket{container=\"public-api\", http_status!=\"404\"}[15m])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "api errors per second by status [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (http_status) (rate(request_count_total{container=\"public-api\", http_status=~\"4..|5..\"}[5m]))",
     "legendFormat": "{{http_status}}"
    }
   ]
  }
 ]
}