{
 "title": "ext - scraper metrics",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Scraper metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "highscore request count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(hiscore_scraper_successes_total{container=\"scraper-highscore\"}[1d]))",
     "legendFormat": "hiscore_scraper_successes_total"
    },
    {
     "expr": "sum(increase(hiscore_scraper_not_found_total{container=\"scraper-highscore\"}[1d]))",
     "legendFormat": "hiscore_scraper_not_found_total"
    }
   ]
  },
  {
   "title": "RuneMetrics error (label_jagex) by error_type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (error_type) (\r\n  increase(runemetrics_scraper_player_update_errors_total{container=\"scraper-runemetrics\"}[1d])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "avg. requests per second [15m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(hiscore_scraper_requests_total{container=\"scraper-highscore\"}[15m]))",
     "legendFormat": "hiscore_scraper_requests"
    },
    {
     "expr": "sum(rate(runemetrics_scraper_requests_total{container=\"scraper-runemetrics\"}[15m]))",
     "legendFormat": "runemetrics_scraper_requests"
    }
   ]
  },
  { "title": "Highscore Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "hiscore_scraper_fetch_latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(hiscore_scraper_fetch_latency_seconds_bucket{container=\"scraper-highscore\"}[15m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(hiscore_scraper_fetch_latency_seconds_bucket{container=\"scraper-highscore\"}[15m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(hiscore_scraper_fetch_latency_seconds_bucket{container=\"scraper-highscore\"}[15m])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "hiscore_scraper_fetch_latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(hiscore_scraper_fetch_latency_seconds_bucket{container=\"scraper-highscore\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Highscore requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(hiscore_scraper_requests_total{container=\"scraper-highscore\"}[$__rate_interval]))",
     "legendFormat": "request_count"
    },
    {
     "expr": "sum(rate(hiscore_scraper_not_found_total{container=\"scraper-highscore\"}[$__rate_interval]))",
     "legendFormat": "not_found_count"
    },
    {
     "expr": "sum(rate(hiscore_scraper_successes_total{container=\"scraper-highscore\"}[$__rate_interval]))",
     "legendFormat": "success_count"
    },
    {
     "expr": "sum(rate(hiscore_scraper_errors_total{container=\"scraper-highscore\"}[$__rate_interval]))",
     "legendFormat": "error_count"
    }
   ]
  },
  { "title": "RuneMetrics Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "runemetrics_scraper_latency_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(runemetrics_scraper_latency_seconds_bucket{container=\"scraper-runemetrics\"}[15m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(runemetrics_scraper_latency_seconds_bucket{container=\"scraper-runemetrics\"}[15m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(runemetrics_scraper_latency_seconds_bucket{container=\"scraper-runemetrics\"}[15m])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "runemetrics_scraper_latency_seconds",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by (le) (\r\n  rate(runemetrics_scraper_latency_seconds_bucket{container=\"scraper-runemetrics\"}[$__rate_interval])\r\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "RuneMetrics error (label_jagex) by error_type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (error_type) (\r\n  rate(runemetrics_scraper_player_update_errors_total{container=\"scraper-runemetrics\"}[$__rate_interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RuneMetrics Request per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(rate(runemetrics_scraper_requests_total{container=\"scraper-runemetrics\"}[$__rate_interval]))",
     "legendFormat": "request_count"
    },
    {
     "expr": "sum(rate(runemetrics_scraper_successes_total{container=\"scraper-runemetrics\"}[$__rate_interval]))",
     "legendFormat": "success_count"
    },
    {
     "expr": "sum(rate(runemetrics_scraper_errors_total{container=\"scraper-runemetrics\"}[$__rate_interval]))",
     "legendFormat": "error_count"
    }
   ]
  }
 ]
}