[build-system]
requires = ["hatchling", "hatch-polylith-bricks"]
build-backend = "hatchling.build"

[project]
name = "worker_report"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
    "asyncmy==0.2.10",
    "cryptography==44.0.1",
    "pydantic-settings==2.7.0",
    "pydantic==2.10.4",
    "sqlalchemy==2.0.37",
    "orjson==3.10.16",
    "aiokafka==0.12.0",
]

[project.scripts]
worker_report = "bot_detector.worker_report.main:run"

# This section is needed for building
[tool.hatch.build.targets.wheel]
packages = ["bot_detector"]

[tool.hatch.build.hooks.polylith-bricks]

[tool.polylith.bricks]
"../../bases/bot_detector/worker_report" = "bot_detector/worker_report"
"../../components/bot_detector/database" = "bot_detector/database"
"../../components/bot_detector/kafka" = "bot_detector/kafka"
"../../components/bot_detector/structs" = "bot_detector/structs"
"../../components/bot_detector/logfmt" = "bot_detector/logfmt"
