from typing import Any, Generic, Optional, Protocol, TypeVar

from pydantic import BaseModel

T = TypeVar("T", bound=BaseModel)  # invariant by default


class ConsumerInterface(Protocol, Generic[T]):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def get_consumer(self) -> Any: ...
    async def consume_one(self) -> tuple[Optional[T], Optional[str]]: ...
    async def consume_many(
        self, max_records: int, timeout_ms: int
    ) -> tuple[list[T], list[str]]: ...
    async def get_lag(self) -> int: ...
