[build-system]
requires = ["hatchling", "hatch-polylith-bricks"]
build-backend = "hatchling.build"

[project]
name = "api_ml"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
    "fastapi>=0.115.12",
    "pydantic-settings>=2.9.1",
    "uvicorn>=0.34.2",
    "prometheus-client>=0.22.0",
    "mlflow>=3.1.4",
    "boto3>=1.40.34",
]

[project.scripts]
scrape_task_producer = "bot_detector.api_ml.core.server:run"

[tool.hatch.build.hooks.polylith-bricks]
packages = ["bot_detector"]

[tool.polylith.bricks]
"../../bases/bot_detector/api_ml" = "bot_detector/api_ml"
"../../components/bot_detector/logfmt" = "bot_detector/logfmt"
