name: build

on:
  workflow_call:
    inputs:
      REGISTRY:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      BUILD_ARGS:
        required: false
        type: string
        default: ""
      DOCKERFILE:
        required: true
        type: string
        default: "Dockerfile"
    secrets:
      QUAY_REGISTERY_PASSWORD:
        required: true

  workflow_dispatch:

jobs:
  build_image:
    runs-on: [self-hosted, "hetzner"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files
        run: ls -lah

      - name: Set variables
        id: vars
        run: |
          echo "GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT

      - name: Docker version
        run: docker --version

      - name: Install Docker Buildx
        run: |
          export BUILDX_URL=https://github.com/docker/buildx/releases/download/v0.31.1/buildx-v0.31.1.linux-amd64
          mkdir -p $HOME/.docker/cli-plugins
          curl -SL $BUILDX_URL -o $HOME/.docker/cli-plugins/docker-buildx
          chmod a+x $HOME/.docker/cli-plugins/docker-buildx
          docker buildx version

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: bot_detector+quay_robot
          password: ${{ secrets.QUAY_REGISTERY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build . \
            --file "${{ inputs.DOCKERFILE }}" \
            ${{ inputs.BUILD_ARGS }} \
            --tag "${{ inputs.REGISTRY }}:${{ steps.vars.outputs.GIT_HASH }}" \
            --tag "${{ inputs.REGISTRY }}:${{ inputs.ENVIRONMENT }}" \
            --push
