name: api_public

on:
  push:
    paths:
      - bases/bot_detector/api_public/**
      - components/bot_detector/kafka/**
      - components/bot_detector/structs/**
      - components/bot_detector/logfmt/**
      - projects/api_public/**
  workflow_dispatch:

jobs:
  common:
    uses: ./.github/workflows/shared/common.yml
    with:
      project_dir: projects/api_public