name: hiscore_scraper

on:
  push:
    paths:
      - bases/bot_detector/hiscore_scraper/**
      - components/bot_detector/proxy_manager/**
      - components/bot_detector/kafka/**
      - components/bot_detector/structs/**
      - components/bot_detector/logfmt/**
      - projects/hiscore_scraper/**
  workflow_dispatch:

jobs:
  common:
    uses: ./.github/workflows/common.yml