name: hiscore_scraper

on:
  push:
    paths:
      - bases/bot_detector/hiscore_scraper/**
      - components/bot_detector/proxy_manager/**
      - components/bot_detector/kafka/**
      - components/bot_detector/structs/**
      - components/bot_detector/logfmt/**
      - projects/hiscore_scraper/**
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy environment'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - deploy to prd

jobs:
  common:
    uses: ./.github/workflows/_common.yml
    with:
      project_dir: projects/hiscore_scraper

  build:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/_build.yml
    needs: common
    with:
      registry: quay.io/bot_detector/scraper-highscore
      environment: ${{ (github.event.inputs.environment == 'deploy to prd' && 'prd') }}
      BUILD_ARGS: "--target=production"
      DOCKERFILE: ./projects/hiscore_scraper/Dockerfile
    secrets:
      QUAY_REGISTERY_PASSWORD: ${{ secrets.QUAY_REGISTERY_PASSWORD }}

  deploy:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/_deploy.yml
    needs: build
    with:
      registry: quay.io/bot_detector/scraper-highscore
      value_file: scraper-highscore-prd/deployment.yaml
    secrets:
      HETZNER_ACTIONS_RUNNER_TOKEN: ${{ secrets.HETZNER_ACTIONS_RUNNER_TOKEN }}