name: worker_hiscore

on:
  push:
    paths:
      - bases/bot_detector/worker_hiscore/**
      - components/bot_detector/database/**
      - components/bot_detector/kafka/**
      - components/bot_detector/structs/**
      - components/bot_detector/logfmt/**
      - projects/worker_hiscore/**
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy environment"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - deploy to prd

jobs:
  common:
    uses: ./.github/workflows/_common.yml
    with:
      project_dir: projects/worker_hiscore

  build:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'deploy to prd' }}
    uses: ./.github/workflows/_build.yml
    needs: common
    with:
      registry: quay.io/bot_detector/highscore-worker
      environment: ${{ (github.event.inputs.environment == 'deploy to prd' && 'prd') }}
      BUILD_ARGS: "--target=prod"
      DOCKERFILE: ./projects/worker_hiscore/Dockerfile
    secrets:
      QUAY_REGISTERY_PASSWORD: ${{ secrets.QUAY_REGISTERY_PASSWORD }}

  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'deploy to prd' }}
    uses: ./.github/workflows/_deploy.yml
    needs: build
    with:
      registry: quay.io/bot_detector/highscore-worker
      value_file: highscore-worker/deployment.yaml
    secrets:
      HETZNER_ACTIONS_RUNNER_TOKEN: ${{ secrets.HETZNER_ACTIONS_RUNNER_TOKEN }}
